### ISSUE TITLE
Checking reaction diffusion rates in different compartments.

### ISSUE THREAD

**Issue by sm1216** [NicolaMelillo/ManchesterPBPK#4]
Is there a way to check the metabolic reactions diffusion rates in different body compartments?

**Comment by NicolaMelillo** [comment]
Hello,

Thanks for your question.
Could you please clarify what you mean with _metabolic reactions diffusion rates_?

In the model, metabolims is supposed to happen either in liver or in kidneys and is determined by the hepatic and renal intrinsic CL, respectively. Allowing the user to include (through the UI) organs specific metabolic reactions is beyond the scope of this _simple_ platform ([OSP suite](https://github.com/Open-Systems-Pharmacology/PK-Sim) allows that!).

Nevertheless, all the equations and parameters are avaialble and they can be easily modified! [This script](https://github.com/NicolaMelillo/ManchesterPBPK/blob/main/main_pbpk_acat.R) allows you to inspect all the model aspects.

As [written here](https://github.com/NicolaMelillo/ManchesterPBPK), this software is now maintained by [SystemsForecasting](https://github.com/SystemsForecasting), please visit [this page](https://github.com/SystemsForecasting/ManchesterPBPK) to access the latest version!

Nicola
